export enum Screen {
  LANDING = 'LANDING',
  SIGNUP_STEP_1 = 'SIGNUP_STEP_1',
  SIGNUP_STEP_2 = 'SIGNUP_STEP_2',
  DASHBOARD = 'DASHBOARD',
  SCHOLARSHIPS = 'SCHOLARSHIPS',
  CAREER_TRACKER = 'CAREER_TRACKER',
  CV_BUILDER = 'CV_BUILDER',
  ATS_CHECKER = 'ATS_CHECKER',
  PRESENTATION = 'PRESENTATION',
  CAREER_TOOLS = 'CAREER_TOOLS',
  ACADEMIC_TOOLS = 'ACADEMIC_TOOLS',
  LEARNING_PLAN = 'LEARNING_PLAN',
  PLAGIARISM = 'PLAGIARISM',
  HABIT_TRACKER = 'HABIT_TRACKER',
  COMMUNITY = 'COMMUNITY',
  CONTACT = 'CONTACT',
  SIGN_IN = 'SIGN_IN',
  BLOG = 'BLOG',
  ABOUT = 'ABOUT',
  PROFILE = 'PROFILE',
  // Admin Screens
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_EMPLOYERS = 'ADMIN_EMPLOYERS',
  ADMIN_TOOLS = 'ADMIN_TOOLS',
  ADMIN_USERS = 'ADMIN_USERS',
  ADMIN_SCHOLARSHIPS = 'ADMIN_SCHOLARSHIPS',
  ADMIN_ROLES = 'ADMIN_ROLES',
  ADMIN_BLOG = 'ADMIN_BLOG',
  ADMIN_SETTINGS = 'ADMIN_SETTINGS',
  ADMIN_NOTIFICATIONS = 'ADMIN_NOTIFICATIONS',
  ADMIN_TEAM = 'ADMIN_TEAM',
  // Admin Analytics
  ADMIN_DEMOGRAPHICS = 'ADMIN_DEMOGRAPHICS',
  // Employer Screens
  EMPLOYER_DASHBOARD = 'EMPLOYER_DASHBOARD',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  // Student Settings
  SETTINGS = 'SETTINGS',
}

export interface NavigationProps {
  navigateTo: (screen: Screen) => void;
}
