/**
 * StudentOS Telegram Bot
 * ─── AI Presentation Maker & Habit Tracker ───
 *
 * Tech: Telegraf, OpenAI, pptxgenjs, dotenv
 * UI: Bottom reply keyboards (persistent buttons)
 */

require('dotenv').config();

const { Telegraf, Markup, Scenes, session } = require('telegraf');
const OpenAI = require('openai');
const PptxGenJS = require('pptxgenjs');

// ─── Validate env ──────────────────────────────────────────
const { BOT_TOKEN, OPENAI_API_KEY, OPENAI_MODEL = 'gpt-4o-mini' } = process.env;

if (!BOT_TOKEN) {
    console.error('❌ BOT_TOKEN is missing in .env');
    process.exit(1);
}
if (!OPENAI_API_KEY) {
    console.error('❌ OPENAI_API_KEY is missing in .env');
    process.exit(1);
}

// ─── Clients ───────────────────────────────────────────────
const openai = new OpenAI({ apiKey: OPENAI_API_KEY });
const bot = new Telegraf(BOT_TOKEN);

// ─── In-memory Habit Store ─────────────────────────────────
const habitsStore = new Map();

function getUserHabits(userId) {
    if (!habitsStore.has(userId)) habitsStore.set(userId, []);
    return habitsStore.get(userId);
}

// ─── Reply Keyboards ──────────────────────────────────────
const mainMenuKb = Markup.keyboard([
    ['📊 Presentation Maker', '🗓 Habit Tracker'],
    ['❓ Help'],
]).resize();

const habitMenuKb = Markup.keyboard([
    ['➕ Add Habit', '📋 My Habits'],
    ['🔙 Main Menu'],
]).resize();

const cancelKb = Markup.keyboard([['❌ Cancel']]).resize();

// ─── PPTX Slide Theme ──────────────────────────────────────
const THEME = {
    bg: '0F172A',
    accent: '6366F1',
    white: 'FFFFFF',
    muted: 'CBD5E1',
    fontFace: 'Segoe UI',
};

/**
 * Generate a real .pptx buffer from slide data
 */
async function generatePptxBuffer(topic, slides) {
    const pptx = new PptxGenJS();
    pptx.author = 'StudentOS Bot';
    pptx.title = topic;
    pptx.layout = 'LAYOUT_WIDE';

    // ── Title slide ──
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: THEME.bg };
    titleSlide.addText(topic, {
        x: 0.8, y: 1.5, w: '85%', h: 2,
        fontSize: 36, fontFace: THEME.fontFace, color: THEME.white, bold: true, align: 'left',
    });
    titleSlide.addText('Generated by StudentOS Bot', {
        x: 0.8, y: 4.0, w: '50%',
        fontSize: 14, fontFace: THEME.fontFace, color: THEME.muted,
    });
    titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0.8, y: 3.6, w: 2.0, h: 0.06, fill: { color: THEME.accent },
    });

    // ── Content slides ──
    slides.forEach((slideData, idx) => {
        const slide = pptx.addSlide();
        slide.background = { color: THEME.bg };

        slide.addText(`${String(idx + 1).padStart(2, '0')}`, {
            x: 0.5, y: 0.3, w: 0.8, h: 0.5,
            fontSize: 13, fontFace: THEME.fontFace, color: THEME.accent, bold: true,
        });

        slide.addShape(pptx.ShapeType.rect, {
            x: 0.5, y: 0.85, w: 1.5, h: 0.05, fill: { color: THEME.accent },
        });

        slide.addText(slideData.title || `Slide ${idx + 1}`, {
            x: 0.5, y: 1.0, w: '90%', h: 0.8,
            fontSize: 24, fontFace: THEME.fontFace, color: THEME.white, bold: true,
        });

        const bullets = (slideData.bullet_points || []).map((bp) => ({
            text: bp,
            options: {
                fontSize: 15, fontFace: THEME.fontFace, color: THEME.muted,
                bullet: { type: 'bullet', color: THEME.accent },
                paraSpaceAfter: 10, lineSpacingMultiple: 1.3,
            },
        }));

        if (bullets.length > 0) {
            slide.addText(bullets, { x: 0.5, y: 2.0, w: '88%', h: 3.5, valign: 'top' });
        }
    });

    return await pptx.write({ outputType: 'nodebuffer' });
}

// ─── SCENE: Presentation Maker ─────────────────────────────
const presentationScene = new Scenes.WizardScene(
    'presentation-wizard',

    // Step 0 → Ask for topic
    async (ctx) => {
        await ctx.reply(
            '📊 *AI Presentation Maker*\n\nSend me the topic for your presentation:',
            { parse_mode: 'Markdown', ...cancelKb }
        );
        return ctx.wizard.next();
    },

    // Step 1 → Receive topic, ask for slide count
    async (ctx) => {
        const topic = ctx.message?.text;

        if (!topic || topic === '❌ Cancel') {
            await ctx.reply('❌ Cancelled.', mainMenuKb);
            return ctx.scene.leave();
        }

        ctx.wizard.state.topic = topic;

        await ctx.reply(
            `📝 Topic: *${topic}*\n\nHow many slides do you want?`,
            {
                parse_mode: 'Markdown',
                ...Markup.inlineKeyboard([
                    Markup.button.callback('5 Slides', 'slides_5'),
                    Markup.button.callback('10 Slides', 'slides_10'),
                    Markup.button.callback('15 Slides', 'slides_15'),
                ]),
            }
        );
        return ctx.wizard.next();
    },

    // Step 2 → Placeholder for button clicks
    async (ctx) => {
        if (ctx.message?.text === '❌ Cancel') {
            await ctx.reply('❌ Cancelled.', mainMenuKb);
            return ctx.scene.leave();
        }
        await ctx.reply('👆 Please click one of the buttons above to choose slide count.');
    }
);

// Handle slide count button clicks inside the wizard
presentationScene.action(/slides_(\d+)/, async (ctx) => {
    const slideCount = parseInt(ctx.match[1], 10);
    const topic = ctx.wizard.state.topic;

    await ctx.answerCbQuery();
    await ctx.editMessageReplyMarkup();

    const statusMsg = await ctx.reply(
        `⏳ Generating a *${slideCount}-slide* presentation about *"${topic}"*...\n\nThis may take 20–30 seconds.`,
        { parse_mode: 'Markdown' }
    );

    try {
        const completion = await openai.chat.completions.create({
            model: OPENAI_MODEL,
            temperature: 0.7,
            max_tokens: 3000,
            messages: [
                {
                    role: 'system',
                    content: `You are an expert presentation creator. Create a structured outline for a presentation. Return ONLY valid JSON — no markdown, no code fences, no extra text. Return a JSON array where each object has "title" (string) and "bullet_points" (array of 3-4 concise strings). No wrapping object — just the array.`,
                },
                {
                    role: 'user',
                    content: `Create a professional presentation about "${topic}" with exactly ${slideCount} slides.`,
                },
            ],
        });

        const raw = completion.choices[0]?.message?.content?.trim();
        if (!raw) throw new Error('Empty AI response');

        const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
        const slidesData = JSON.parse(cleaned);

        if (!Array.isArray(slidesData) || slidesData.length === 0) {
            throw new Error('Invalid slide data from AI');
        }

        await ctx.telegram.editMessageText(
            ctx.chat.id, statusMsg.message_id, undefined,
            '🎨 Building your PowerPoint file...'
        );

        const pptxBuffer = await generatePptxBuffer(topic, slidesData);
        const safeName = topic.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_');

        await ctx.replyWithDocument(
            { source: pptxBuffer, filename: `${safeName || 'Presentation'}.pptx` },
            {
                caption: `✅ *${topic}*\n${slidesData.length} slides generated!\n\nOpen in PowerPoint or Google Slides.`,
                parse_mode: 'Markdown',
                ...mainMenuKb,
            }
        );

        try { await ctx.telegram.deleteMessage(ctx.chat.id, statusMsg.message_id); } catch { /* ignore */ }
    } catch (err) {
        console.error('Presentation generation failed:', err);
        const errMsg = err.code === 'insufficient_quota'
            ? '💳 OpenAI quota exceeded. Please check your API billing.'
            : `❌ Something went wrong.\n\n_${err.message || 'Unknown error'}_`;
        await ctx.reply(errMsg, { parse_mode: 'Markdown', ...mainMenuKb });
    }

    return ctx.scene.leave();
});

// Cancel inside presentation wizard
presentationScene.hears('❌ Cancel', async (ctx) => {
    await ctx.reply('❌ Cancelled.', mainMenuKb);
    return ctx.scene.leave();
});

// ─── SCENE: Add Habit ──────────────────────────────────────
const addHabitScene = new Scenes.WizardScene(
    'add-habit-wizard',

    async (ctx) => {
        await ctx.reply('➕ *Add a new habit*\n\nSend me the name of the habit:', {
            parse_mode: 'Markdown',
            ...cancelKb,
        });
        return ctx.wizard.next();
    },

    async (ctx) => {
        const name = ctx.message?.text?.trim();

        if (!name || name === '❌ Cancel') {
            await ctx.reply('❌ Cancelled.', habitMenuKb);
            return ctx.scene.leave();
        }

        if (name.length > 100) {
            await ctx.reply('❌ Too long. Keep it under 100 characters.');
            return;
        }

        const userId = ctx.from.id;
        const habits = getUserHabits(userId);

        if (habits.some((h) => h.name.toLowerCase() === name.toLowerCase())) {
            await ctx.reply(`⚠️ You already have *"${name}"*.`, {
                parse_mode: 'Markdown', ...habitMenuKb,
            });
            return ctx.scene.leave();
        }

        habits.push({ name, streak: 0, lastDone: null });

        await ctx.reply(
            `✅ Habit *"${name}"* added!\n\n🔥 Streak: 0 days`,
            { parse_mode: 'Markdown', ...habitMenuKb }
        );

        return ctx.scene.leave();
    }
);

addHabitScene.hears('❌ Cancel', async (ctx) => {
    await ctx.reply('❌ Cancelled.', habitMenuKb);
    return ctx.scene.leave();
});

// ─── Scene Stage ───────────────────────────────────────────
const stage = new Scenes.Stage([presentationScene, addHabitScene]);

bot.use(session());
bot.use(stage.middleware());

// ─── Helpers ───────────────────────────────────────────────
function getToday() {
    return new Date().toISOString().slice(0, 10);
}

async function sendMainMenu(ctx) {
    await ctx.reply(
        '🎓 *StudentOS Bot*\n\nChoose a tool to get started:',
        { parse_mode: 'Markdown', ...mainMenuKb }
    );
}

async function showHabitList(ctx) {
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);

    if (habits.length === 0) {
        return ctx.reply('📋 You have no habits yet!\n\nTap ➕ Add Habit to create one.', habitMenuKb);
    }

    const today = getToday();
    const buttons = habits.map((h, idx) => {
        const doneToday = h.lastDone === today;
        const label = `${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`;
        return [Markup.button.callback(label, `toggle_${idx}`)];
    });
    buttons.push([Markup.button.callback('🗑 Delete a Habit', 'delete_menu')]);

    await ctx.reply('📋 *Your Habits*\n\nTap to mark done for today:', {
        parse_mode: 'Markdown',
        ...Markup.inlineKeyboard(buttons),
    });
}

// ─── Bot Commands ──────────────────────────────────────────
bot.start(async (ctx) => {
    await ctx.reply(
        `👋 Welcome, *${ctx.from.first_name}*!\n\nI can create AI presentations and track your habits.`,
        { parse_mode: 'Markdown', ...mainMenuKb }
    );
});

bot.command('menu', sendMainMenu);

bot.command('help', async (ctx) => {
    await ctx.reply(
        `🎓 *StudentOS Bot — Help*\n\n` +
        `📊 *Presentation Maker* — AI-powered PowerPoint creation\n` +
        `🗓 *Habit Tracker* — Daily habits with streak tracking\n\n` +
        `Use the buttons at the bottom to navigate!`,
        { parse_mode: 'Markdown', ...mainMenuKb }
    );
});

// ─── Main Menu (Reply Keyboard) ────────────────────────────
bot.hears('📊 Presentation Maker', (ctx) => ctx.scene.enter('presentation-wizard'));

bot.hears('🗓 Habit Tracker', async (ctx) => {
    await ctx.reply('🗓 *Habit Tracker*\n\nWhat would you like to do?', {
        parse_mode: 'Markdown',
        ...habitMenuKb,
    });
});

bot.hears('❓ Help', async (ctx) => {
    await ctx.reply(
        `🎓 *StudentOS Bot — Help*\n\n` +
        `📊 *Presentation Maker* — AI-powered PowerPoint creation\n` +
        `🗓 *Habit Tracker* — Daily habits with streak tracking\n\n` +
        `Use the buttons at the bottom to navigate!`,
        { parse_mode: 'Markdown', ...mainMenuKb }
    );
});

bot.hears('🔙 Main Menu', sendMainMenu);

// ─── Habit Tracker (Reply Keyboard) ────────────────────────
bot.hears('➕ Add Habit', (ctx) => ctx.scene.enter('add-habit-wizard'));
bot.hears('📋 My Habits', showHabitList);

// ─── Habit Tracker (Inline Actions — stay inline for toggles) ──
bot.action(/toggle_(\d+)/, async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);
    const idx = parseInt(ctx.match[1], 10);

    if (idx >= habits.length) return;

    const habit = habits[idx];
    const today = getToday();

    if (habit.lastDone === today) {
        habit.streak = Math.max(0, habit.streak - 1);
        habit.lastDone = null;
    } else {
        const yesterday = new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        const yesterdayStr = yesterday.toISOString().slice(0, 10);

        if (habit.lastDone === yesterdayStr || habit.streak === 0) {
            habit.streak += 1;
        } else {
            habit.streak = 1;
        }
        habit.lastDone = today;
    }

    // Refresh inline buttons
    const buttons = habits.map((h, i) => {
        const doneToday = h.lastDone === today;
        return [Markup.button.callback(`${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`, `toggle_${i}`)];
    });
    buttons.push([Markup.button.callback('🗑 Delete a Habit', 'delete_menu')]);

    try {
        await ctx.editMessageText('📋 *Your Habits*\n\nTap to mark done for today:', {
            parse_mode: 'Markdown',
            ...Markup.inlineKeyboard(buttons),
        });
    } catch { /* message not modified */ }
});

// Delete habit menu
bot.action('delete_menu', async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);

    if (habits.length === 0) return ctx.reply('No habits to delete.', habitMenuKb);

    const buttons = habits.map((h, idx) => [
        Markup.button.callback(`🗑 ${h.name}`, `del_${idx}`),
    ]);
    buttons.push([Markup.button.callback('⬅️ Back', 'back_to_habits')]);

    await ctx.editMessageText('🗑 *Delete a Habit*\n\nTap to remove:', {
        parse_mode: 'Markdown',
        ...Markup.inlineKeyboard(buttons),
    });
});

bot.action(/del_(\d+)/, async (ctx) => {
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);
    const idx = parseInt(ctx.match[1], 10);

    if (idx >= habits.length) return ctx.answerCbQuery('Not found');

    const removed = habits.splice(idx, 1)[0];
    await ctx.answerCbQuery(`Deleted "${removed.name}"`);

    if (habits.length > 0) {
        const today = getToday();
        const buttons = habits.map((h, i) => {
            const doneToday = h.lastDone === today;
            return [Markup.button.callback(`${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`, `toggle_${i}`)];
        });
        buttons.push([Markup.button.callback('🗑 Delete a Habit', 'delete_menu')]);

        await ctx.editMessageText('📋 *Your Habits*\n\nTap to mark done for today:', {
            parse_mode: 'Markdown',
            ...Markup.inlineKeyboard(buttons),
        });
    } else {
        await ctx.editMessageText('🗑 All habits deleted.');
    }
});

bot.action('back_to_habits', async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);
    const today = getToday();

    const buttons = habits.map((h, i) => {
        const doneToday = h.lastDone === today;
        return [Markup.button.callback(`${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`, `toggle_${i}`)];
    });
    buttons.push([Markup.button.callback('🗑 Delete a Habit', 'delete_menu')]);

    await ctx.editMessageText('📋 *Your Habits*\n\nTap to mark done for today:', {
        parse_mode: 'Markdown',
        ...Markup.inlineKeyboard(buttons),
    });
});

// ─── Global cancel ─────────────────────────────────────────
bot.command('cancel', async (ctx) => {
    await ctx.reply('❌ Cancelled.', mainMenuKb);
});

// ─── Error handling ────────────────────────────────────────
bot.catch((err, ctx) => {
    console.error(`Bot error for ${ctx.updateType}:`, err);
    ctx.reply('⚠️ An unexpected error occurred. Use /start to restart.', mainMenuKb);
});

// ─── Launch ────────────────────────────────────────────────
bot.launch()
    .then(() => {
        console.log('');
        console.log('  ┌──────────────────────────────────────────┐');
        console.log('  │   🤖 StudentOS Telegram Bot is running   │');
        console.log('  │   Presentation Maker ✅  Habit Tracker ✅ │');
        console.log('  │   Mode: Reply Keyboard (bottom buttons)  │');
        console.log('  └──────────────────────────────────────────┘');
        console.log('');
    })
    .catch((err) => {
        console.error('Failed to launch bot:', err);
        process.exit(1);
    });

process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
