/**
 * StudentOS Telegram Bot
 * ─── AI Presentation Maker & Habit Tracker ───
 *
 * Tech: Telegraf, OpenAI, pptxgenjs, dotenv
 */

require('dotenv').config();

const { Telegraf, Markup, Scenes, session } = require('telegraf');
const OpenAI = require('openai');
const PptxGenJS = require('pptxgenjs');

// ─── Validate env ──────────────────────────────────────────
const { BOT_TOKEN, OPENAI_API_KEY, OPENAI_MODEL = 'gpt-4o-mini' } = process.env;

if (!BOT_TOKEN) {
    console.error('❌ BOT_TOKEN is missing in .env');
    process.exit(1);
}
if (!OPENAI_API_KEY) {
    console.error('❌ OPENAI_API_KEY is missing in .env');
    process.exit(1);
}

// ─── Clients ───────────────────────────────────────────────
const openai = new OpenAI({ apiKey: OPENAI_API_KEY });
const bot = new Telegraf(BOT_TOKEN);

// ─── In-memory Habit Store ─────────────────────────────────
// Map<userId, { name: string, streak: number, lastDone: string|null }[]>
const habitsStore = new Map();

function getUserHabits(userId) {
    if (!habitsStore.has(userId)) habitsStore.set(userId, []);
    return habitsStore.get(userId);
}

// ─── PPTX Slide Theme ──────────────────────────────────────
const THEME = {
    bg: '0F172A',          // dark navy
    accent: '6366F1',      // indigo-500
    white: 'FFFFFF',
    muted: 'CBD5E1',       // slate-300
    fontFace: 'Segoe UI',
};

/**
 * Generate a real .pptx buffer from slide data
 * @param {string} topic
 * @param {{ title: string, bullet_points: string[] }[]} slides
 * @returns {Promise<Buffer>}
 */
async function generatePptxBuffer(topic, slides) {
    const pptx = new PptxGenJS();
    pptx.author = 'StudentOS Bot';
    pptx.title = topic;
    pptx.layout = 'LAYOUT_WIDE'; // 16:9

    // ── Title slide ──
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: THEME.bg };
    titleSlide.addText(topic, {
        x: 0.8,
        y: 1.5,
        w: '85%',
        h: 2,
        fontSize: 36,
        fontFace: THEME.fontFace,
        color: THEME.white,
        bold: true,
        align: 'left',
    });
    titleSlide.addText('Generated by StudentOS Bot', {
        x: 0.8,
        y: 4.0,
        w: '50%',
        fontSize: 14,
        fontFace: THEME.fontFace,
        color: THEME.muted,
    });
    titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 3.6,
        w: 2.0,
        h: 0.06,
        fill: { color: THEME.accent },
    });

    // ── Content slides ──
    slides.forEach((slideData, idx) => {
        const slide = pptx.addSlide();
        slide.background = { color: THEME.bg };

        // Slide number badge
        slide.addText(`${String(idx + 1).padStart(2, '0')}`, {
            x: 0.5,
            y: 0.3,
            w: 0.8,
            h: 0.5,
            fontSize: 13,
            fontFace: THEME.fontFace,
            color: THEME.accent,
            bold: true,
        });

        // Accent bar
        slide.addShape(pptx.ShapeType.rect, {
            x: 0.5,
            y: 0.85,
            w: 1.5,
            h: 0.05,
            fill: { color: THEME.accent },
        });

        // Slide title
        slide.addText(slideData.title || `Slide ${idx + 1}`, {
            x: 0.5,
            y: 1.0,
            w: '90%',
            h: 0.8,
            fontSize: 24,
            fontFace: THEME.fontFace,
            color: THEME.white,
            bold: true,
        });

        // Bullet points
        const bullets = (slideData.bullet_points || []).map((bp) => ({
            text: bp,
            options: {
                fontSize: 15,
                fontFace: THEME.fontFace,
                color: THEME.muted,
                bullet: { type: 'bullet', color: THEME.accent },
                paraSpaceAfter: 10,
                lineSpacingMultiple: 1.3,
            },
        }));

        if (bullets.length > 0) {
            slide.addText(bullets, {
                x: 0.5,
                y: 2.0,
                w: '88%',
                h: 3.5,
                valign: 'top',
            });
        }
    });

    // Return buffer
    return await pptx.write({ outputType: 'nodebuffer' });
}

// ─── SCENE: Presentation Maker ─────────────────────────────
const presentationScene = new Scenes.WizardScene(
    'presentation-wizard',

    // Step 0 → Ask for topic
    async (ctx) => {
        await ctx.reply(
            '📊 *AI Presentation Maker*\n\nSend me the topic for your presentation:',
            { parse_mode: 'Markdown' }
        );
        return ctx.wizard.next();
    },

    // Step 1 → Receive topic, ask for slide count
    async (ctx) => {
        const topic = ctx.message?.text;
        if (!topic) {
            await ctx.reply('❌ Please send a text topic.');
            return;
        }

        ctx.wizard.state.topic = topic;

        await ctx.reply(
            `📝 Topic: *${topic}*\n\nHow many slides do you want?`,
            {
                parse_mode: 'Markdown',
                ...Markup.inlineKeyboard([
                    Markup.button.callback('5 Slides', 'slides_5'),
                    Markup.button.callback('10 Slides', 'slides_10'),
                    Markup.button.callback('15 Slides', 'slides_15'),
                ]),
            }
        );
        return ctx.wizard.next();
    },

    // Step 2 → Receive slide count (handled via action, this is a placeholder)
    async (ctx) => {
        // If someone types instead of clicking the button
        await ctx.reply('👆 Please click one of the buttons above to choose slide count.');
    }
);

// Handle slide count button clicks inside the wizard
presentationScene.action(/slides_(\d+)/, async (ctx) => {
    const slideCount = parseInt(ctx.match[1], 10);
    const topic = ctx.wizard.state.topic;

    await ctx.answerCbQuery();
    await ctx.editMessageReplyMarkup(); // Remove buttons

    const statusMsg = await ctx.reply(
        `⏳ Generating a *${slideCount}-slide* presentation about *"${topic}"*...\n\nThis may take 20–30 seconds.`,
        { parse_mode: 'Markdown' }
    );

    try {
        // ── Call OpenAI ──
        const completion = await openai.chat.completions.create({
            model: OPENAI_MODEL,
            temperature: 0.7,
            max_tokens: 3000,
            messages: [
                {
                    role: 'system',
                    content: `You are an expert presentation creator. Create a structured outline for a presentation. Return ONLY valid JSON — no markdown, no code fences, no extra text. Return a JSON array where each object has "title" (string) and "bullet_points" (array of 3-4 concise strings). No wrapping object — just the array.`,
                },
                {
                    role: 'user',
                    content: `Create a professional presentation about "${topic}" with exactly ${slideCount} slides.`,
                },
            ],
        });

        const raw = completion.choices[0]?.message?.content?.trim();
        if (!raw) throw new Error('Empty AI response');

        // Parse JSON (strip code fences if AI adds them)
        const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
        const slidesData = JSON.parse(cleaned);

        if (!Array.isArray(slidesData) || slidesData.length === 0) {
            throw new Error('Invalid slide data from AI');
        }

        // ── Generate PPTX ──
        await ctx.telegram.editMessageText(
            ctx.chat.id,
            statusMsg.message_id,
            undefined,
            '🎨 Building your PowerPoint file...'
        );

        const pptxBuffer = await generatePptxBuffer(topic, slidesData);

        // ── Send file ──
        const safeName = topic.replace(/[^a-zA-Z0-9 ]/g, '').trim().replace(/\s+/g, '_');
        await ctx.replyWithDocument(
            {
                source: pptxBuffer,
                filename: `${safeName || 'Presentation'}.pptx`,
            },
            {
                caption: `✅ *${topic}*\n${slidesData.length} slides generated successfully!\n\nOpen in PowerPoint or Google Slides.`,
                parse_mode: 'Markdown',
            }
        );

        // Clean up status message
        try {
            await ctx.telegram.deleteMessage(ctx.chat.id, statusMsg.message_id);
        } catch {
            /* ignore */
        }
    } catch (err) {
        console.error('Presentation generation failed:', err);

        const errMsg =
            err.code === 'insufficient_quota'
                ? '💳 OpenAI quota exceeded. Please check your API billing.'
                : `❌ Something went wrong while generating your presentation.\n\n_${err.message || 'Unknown error'}_`;

        await ctx.reply(errMsg, { parse_mode: 'Markdown' });
    }

    return ctx.scene.leave();
});

// Let user cancel at any point
presentationScene.command('cancel', async (ctx) => {
    await ctx.reply('❌ Presentation creation cancelled.', mainMenuKeyboard());
    return ctx.scene.leave();
});

presentationScene.action('main_menu', async (ctx) => {
    await ctx.answerCbQuery();
    await ctx.scene.leave();
    return sendMainMenu(ctx);
});

// ─── SCENE: Add Habit ──────────────────────────────────────
const addHabitScene = new Scenes.WizardScene(
    'add-habit-wizard',

    async (ctx) => {
        await ctx.reply('➕ *Add a new habit*\n\nSend me the name of the habit:', {
            parse_mode: 'Markdown',
        });
        return ctx.wizard.next();
    },

    async (ctx) => {
        const name = ctx.message?.text?.trim();
        if (!name) {
            await ctx.reply('❌ Please send a text name for your habit.');
            return;
        }

        if (name.length > 100) {
            await ctx.reply('❌ Habit name is too long. Keep it under 100 characters.');
            return;
        }

        const userId = ctx.from.id;
        const habits = getUserHabits(userId);

        // Check for duplicates
        if (habits.some((h) => h.name.toLowerCase() === name.toLowerCase())) {
            await ctx.reply(`⚠️ You already have a habit called "*${name}*".`, {
                parse_mode: 'Markdown',
            });
            return ctx.scene.leave();
        }

        habits.push({
            name,
            streak: 0,
            lastDone: null,
        });

        await ctx.reply(`✅ Habit *"${name}"* added successfully!\n\n🔥 Current streak: 0 days`, {
            parse_mode: 'Markdown',
            ...Markup.inlineKeyboard([
                Markup.button.callback('📋 View My Habits', 'my_habits'),
                Markup.button.callback('🏠 Main Menu', 'main_menu'),
            ]),
        });

        return ctx.scene.leave();
    }
);

addHabitScene.command('cancel', async (ctx) => {
    await ctx.reply('❌ Cancelled.', mainMenuKeyboard());
    return ctx.scene.leave();
});

// ─── Scene Stage ───────────────────────────────────────────
const stage = new Scenes.Stage([presentationScene, addHabitScene]);

bot.use(session());
bot.use(stage.middleware());

// ─── Helpers ───────────────────────────────────────────────
function mainMenuKeyboard() {
    return Markup.inlineKeyboard([
        [Markup.button.callback('📊 Presentation Maker', 'presentation_maker')],
        [Markup.button.callback('🗓 Habit Tracker', 'habit_tracker')],
    ]);
}

async function sendMainMenu(ctx) {
    await ctx.reply(
        '🎓 *StudentOS Bot*\n\nChoose a tool to get started:',
        {
            parse_mode: 'Markdown',
            ...mainMenuKeyboard(),
        }
    );
}

function getToday() {
    return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

// ─── Bot Commands ──────────────────────────────────────────
bot.start(async (ctx) => {
    await ctx.reply(
        `👋 Welcome to *StudentOS Bot*, ${ctx.from.first_name}!\n\nI can help you create AI-powered presentations and track your daily habits.`,
        { parse_mode: 'Markdown' }
    );
    await sendMainMenu(ctx);
});

bot.command('menu', sendMainMenu);
bot.command('help', async (ctx) => {
    await ctx.reply(
        `🎓 *StudentOS Bot — Help*\n\n` +
        `📊 *Presentation Maker* — Create professional PowerPoint presentations with AI. Just provide a topic and slide count!\n\n` +
        `🗓 *Habit Tracker* — Add habits, mark them done daily, and build streaks.\n\n` +
        `*Commands:*\n` +
        `/start — Restart the bot\n` +
        `/menu — Show main menu\n` +
        `/help — This help message\n` +
        `/cancel — Cancel current action`,
        { parse_mode: 'Markdown' }
    );
});

// ─── Main Menu Actions ─────────────────────────────────────
bot.action('presentation_maker', async (ctx) => {
    await ctx.answerCbQuery();
    return ctx.scene.enter('presentation-wizard');
});

bot.action('habit_tracker', async (ctx) => {
    await ctx.answerCbQuery();
    await ctx.reply(
        '🗓 *Habit Tracker*\n\nWhat would you like to do?',
        {
            parse_mode: 'Markdown',
            ...Markup.inlineKeyboard([
                [Markup.button.callback('➕ Add Habit', 'add_habit')],
                [Markup.button.callback('📋 My Habits', 'my_habits')],
                [Markup.button.callback('🏠 Main Menu', 'main_menu')],
            ]),
        }
    );
});

bot.action('main_menu', async (ctx) => {
    await ctx.answerCbQuery();
    return sendMainMenu(ctx);
});

// ─── Habit Tracker Actions ─────────────────────────────────
bot.action('add_habit', async (ctx) => {
    await ctx.answerCbQuery();
    return ctx.scene.enter('add-habit-wizard');
});

bot.action('my_habits', async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);

    if (habits.length === 0) {
        return ctx.reply(
            '📋 You have no habits yet!\n\nAdd one to get started.',
            Markup.inlineKeyboard([
                Markup.button.callback('➕ Add Habit', 'add_habit'),
                Markup.button.callback('🏠 Main Menu', 'main_menu'),
            ])
        );
    }

    const today = getToday();
    const buttons = habits.map((h, idx) => {
        const doneToday = h.lastDone === today;
        const label = `${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`;
        return [Markup.button.callback(label, `toggle_habit_${idx}`)];
    });

    buttons.push([Markup.button.callback('➕ Add More', 'add_habit')]);
    buttons.push([
        Markup.button.callback('🗑 Delete a Habit', 'delete_habit_menu'),
        Markup.button.callback('🏠 Menu', 'main_menu'),
    ]);

    await ctx.reply('📋 *Your Habits*\n\nTap to mark done for today:', {
        parse_mode: 'Markdown',
        ...Markup.inlineKeyboard(buttons),
    });
});

// Toggle habit done
bot.action(/toggle_habit_(\d+)/, async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);
    const idx = parseInt(ctx.match[1], 10);

    if (idx >= habits.length) return;

    const habit = habits[idx];
    const today = getToday();

    if (habit.lastDone === today) {
        // Undo today's check
        habit.streak = Math.max(0, habit.streak - 1);
        habit.lastDone = null;
        await ctx.answerCbQuery(`Unmarked "${habit.name}"`);
    } else {
        // Check if streak continues from yesterday
        const yesterday = new Date();
        yesterday.setDate(yesterday.getDate() - 1);
        const yesterdayStr = yesterday.toISOString().slice(0, 10);

        if (habit.lastDone === yesterdayStr || habit.streak === 0) {
            habit.streak += 1;
        } else {
            habit.streak = 1; // Reset streak
        }
        habit.lastDone = today;
        await ctx.answerCbQuery(`✅ "${habit.name}" — ${habit.streak} day streak!`);
    }

    // Refresh the list
    const buttons = habits.map((h, i) => {
        const doneToday = h.lastDone === today;
        const label = `${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`;
        return [Markup.button.callback(label, `toggle_habit_${i}`)];
    });
    buttons.push([Markup.button.callback('➕ Add More', 'add_habit')]);
    buttons.push([
        Markup.button.callback('🗑 Delete', 'delete_habit_menu'),
        Markup.button.callback('🏠 Menu', 'main_menu'),
    ]);

    try {
        await ctx.editMessageText('📋 *Your Habits*\n\nTap to mark done for today:', {
            parse_mode: 'Markdown',
            ...Markup.inlineKeyboard(buttons),
        });
    } catch {
        /* message not modified — ignore */
    }
});

// Delete habit menu
bot.action('delete_habit_menu', async (ctx) => {
    await ctx.answerCbQuery();
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);

    if (habits.length === 0) {
        return ctx.reply('No habits to delete.');
    }

    const buttons = habits.map((h, idx) => [
        Markup.button.callback(`🗑 ${h.name}`, `delete_habit_${idx}`),
    ]);
    buttons.push([Markup.button.callback('⬅️ Back', 'my_habits')]);

    await ctx.reply('🗑 *Delete a Habit*\n\nTap the habit to remove:', {
        parse_mode: 'Markdown',
        ...Markup.inlineKeyboard(buttons),
    });
});

bot.action(/delete_habit_(\d+)/, async (ctx) => {
    const userId = ctx.from.id;
    const habits = getUserHabits(userId);
    const idx = parseInt(ctx.match[1], 10);

    if (idx >= habits.length) return ctx.answerCbQuery('Habit not found');

    const removed = habits.splice(idx, 1)[0];
    await ctx.answerCbQuery(`Deleted "${removed.name}"`);
    await ctx.editMessageText(`🗑 Deleted *"${removed.name}"*`, { parse_mode: 'Markdown' });

    // Show remaining habits
    if (habits.length > 0) {
        const today = getToday();
        const buttons = habits.map((h, i) => {
            const doneToday = h.lastDone === today;
            return [Markup.button.callback(`${doneToday ? '✅' : '⬜'} ${h.name}  (🔥${h.streak})`, `toggle_habit_${i}`)];
        });
        buttons.push([Markup.button.callback('🏠 Menu', 'main_menu')]);
        await ctx.reply('📋 Remaining habits:', Markup.inlineKeyboard(buttons));
    } else {
        await sendMainMenu(ctx);
    }
});

// ─── Global cancel ─────────────────────────────────────────
bot.command('cancel', async (ctx) => {
    await ctx.reply('❌ Action cancelled.', mainMenuKeyboard());
});

// ─── Error handling ────────────────────────────────────────
bot.catch((err, ctx) => {
    console.error(`Bot error for ${ctx.updateType}:`, err);
    ctx.reply('⚠️ An unexpected error occurred. Please try again or use /start.');
});

// ─── Launch ────────────────────────────────────────────────
bot.launch()
    .then(() => {
        console.log('');
        console.log('  ┌──────────────────────────────────────────┐');
        console.log('  │   🤖 StudentOS Telegram Bot is running   │');
        console.log('  │   Presentation Maker ✅  Habit Tracker ✅ │');
        console.log('  └──────────────────────────────────────────┘');
        console.log('');
    })
    .catch((err) => {
        console.error('Failed to launch bot:', err);
        process.exit(1);
    });

// Graceful shutdown
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
